name: MSDO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sample:
    name: Microsoft Security DevOps
    runs-on: windows-latest

    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write

    steps:
      # Checkout your code repository to scan
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run analyzers
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@latest
        id: msdo
        # with:
        #   config: .gdnconfig
        #   policy: GitHub
        #   categories: IaC, containers
        #   languages: javascript,typescript
        #   tools: bandit,eslint

      # Upload alerts to Security tab
      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      # Upload alerts file as a workflow artifact
      - name: Upload alerts file as a workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: alerts
          path: ${{ steps.msdo.outputs.sarifFile }}
